//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FusionExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FusionExplorer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FusionExplorer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FusionExplorer.Properties.FusionExplorer", typeof(FusionExplorer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Raon Hook.
        /// </summary>
        internal static string ABOUT_CREATOR {
            get {
                return ResourceManager.GetString("ABOUT_CREATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The purpose of this application is the research and modification of the Trials Fusion game files..
        /// </summary>
        internal static string ABOUT_TEXT {
            get {
                return ResourceManager.GetString("ABOUT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string ABOUT_TITLE {
            get {
                return ResourceManager.GetString("ABOUT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nVersion 1.0.3.
        /// </summary>
        internal static string ABOUT_VERSION {
            get {
                return ResourceManager.GetString("ABOUT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string DROP_DOWN_BUTTON_FILE {
            get {
                return ResourceManager.GetString("DROP_DOWN_BUTTON_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Object.
        /// </summary>
        internal static string FE_ADD_OBJECT {
            get {
                return ResourceManager.GetString("FE_ADD_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string FE_COLOR {
            get {
                return ResourceManager.GetString("FE_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emission.
        /// </summary>
        internal static string FE_COLOR_EMISSION {
            get {
                return ResourceManager.GetString("FE_COLOR_EMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Part.
        /// </summary>
        internal static string FE_COLOR_PART {
            get {
                return ResourceManager.GetString("FE_COLOR_PART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Picker.
        /// </summary>
        internal static string FE_COLOR_PICKER {
            get {
                return ResourceManager.GetString("FE_COLOR_PICKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        internal static string FE_COLOR_PRIMARY {
            get {
                return ResourceManager.GetString("FE_COLOR_PRIMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roughness.
        /// </summary>
        internal static string FE_COLOR_ROUGHNESS {
            get {
                return ResourceManager.GetString("FE_COLOR_ROUGHNESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        internal static string FE_COLOR_SECONDARY {
            get {
                return ResourceManager.GetString("FE_COLOR_SECONDARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress GRP.
        /// </summary>
        internal static string FE_COMPRESS_GRP {
            get {
                return ResourceManager.GetString("FE_COMPRESS_GRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompress.
        /// </summary>
        internal static string FE_DECOMPRESS {
            get {
                return ResourceManager.GetString("FE_DECOMPRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoration Only.
        /// </summary>
        internal static string FE_DECORATION_ONLY {
            get {
                return ResourceManager.GetString("FE_DECORATION_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dont Reset Position.
        /// </summary>
        internal static string FE_DONT_RESET_POSITION {
            get {
                return ResourceManager.GetString("FE_DONT_RESET_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Object.
        /// </summary>
        internal static string FE_FAST_OBJECT {
            get {
                return ResourceManager.GetString("FE_FAST_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite Editor.
        /// </summary>
        internal static string FE_FAVOURITE_EDITOR {
            get {
                return ResourceManager.GetString("FE_FAVOURITE_EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourites List.
        /// </summary>
        internal static string FE_FAVOURITES_LIST {
            get {
                return ResourceManager.GetString("FE_FAVOURITES_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit Response.
        /// </summary>
        internal static string FE_HIT_RESPONSE {
            get {
                return ResourceManager.GetString("FE_HIT_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial State.
        /// </summary>
        internal static string FE_INITIAL_STATE {
            get {
                return ResourceManager.GetString("FE_INITIAL_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invisible.
        /// </summary>
        internal static string FE_INVISIBLE {
            get {
                return ResourceManager.GetString("FE_INVISIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Options.
        /// </summary>
        internal static string FE_LIST_OPTIONS {
            get {
                return ResourceManager.GetString("FE_LIST_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock to Driving Line.
        /// </summary>
        internal static string FE_LOCK_TO_DRIVING_LINE {
            get {
                return ResourceManager.GetString("FE_LOCK_TO_DRIVING_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Collision.
        /// </summary>
        internal static string FE_NO_COLLISION {
            get {
                return ResourceManager.GetString("FE_NO_COLLISION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Collision Sound.
        /// </summary>
        internal static string FE_NO_COLLISION_SOUND {
            get {
                return ResourceManager.GetString("FE_NO_COLLISION_SOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Contact Response.
        /// </summary>
        internal static string FE_NO_CONTACAT_RESPONSE {
            get {
                return ResourceManager.GetString("FE_NO_CONTACAT_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Hit Response.
        /// </summary>
        internal static string FE_NO_HIT_RESPONSE {
            get {
                return ResourceManager.GetString("FE_NO_HIT_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Default Physics.
        /// </summary>
        internal static string FE_NON_DEFAULT_PHYSICS {
            get {
                return ResourceManager.GetString("FE_NON_DEFAULT_PHYSICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Directory.
        /// </summary>
        internal static string FE_OPEN_DIRECTORY {
            get {
                return ResourceManager.GetString("FE_OPEN_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string FE_OPTIONS {
            get {
                return ResourceManager.GetString("FE_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physics.
        /// </summary>
        internal static string FE_PHYSICS {
            get {
                return ResourceManager.GetString("FE_PHYSICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string FE_PROPERTIES {
            get {
                return ResourceManager.GetString("FE_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh List.
        /// </summary>
        internal static string FE_REFRESH_LIST {
            get {
                return ResourceManager.GetString("FE_REFRESH_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string FE_SAVE {
            get {
                return ResourceManager.GetString("FE_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As (Compressed).
        /// </summary>
        internal static string FE_SAVE_AS_COMPRESSED {
            get {
                return ResourceManager.GetString("FE_SAVE_AS_COMPRESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As (Decompressed).
        /// </summary>
        internal static string FE_SAVE_AS_DECOMPRESSED {
            get {
                return ResourceManager.GetString("FE_SAVE_AS_DECOMPRESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string FE_SAVE_DONE {
            get {
                return ResourceManager.GetString("FE_SAVE_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Color.
        /// </summary>
        internal static string FE_SET_COLOR {
            get {
                return ResourceManager.GetString("FE_SET_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Properties.
        /// </summary>
        internal static string FE_SET_PROPERTIES {
            get {
                return ResourceManager.GetString("FE_SET_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find object..
        /// </summary>
        internal static string FE_TRY_FIND_OBJECT_FAIL_TEXT {
            get {
                return ResourceManager.GetString("FE_TRY_FIND_OBJECT_FAIL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Object ID.
        /// </summary>
        internal static string FE_TRY_FIND_OBJECT_FAIL_TITLE {
            get {
                return ResourceManager.GetString("FE_TRY_FIND_OBJECT_FAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read Object ID, Ensure the ID is correct..
        /// </summary>
        internal static string FE_TRY_READ_ID_FAIL {
            get {
                return ResourceManager.GetString("FE_TRY_READ_ID_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string FILE_ABOUT {
            get {
                return ResourceManager.GetString("FILE_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string FILE_CLOSE {
            get {
                return ResourceManager.GetString("FILE_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string FILE_OPEN {
            get {
                return ResourceManager.GetString("FILE_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string FILE_SAVE {
            get {
                return ResourceManager.GetString("FILE_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string FILE_TOOLS {
            get {
                return ResourceManager.GetString("FILE_TOOLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Builder.
        /// </summary>
        internal static string FILE_TOOLS_ARCHIVE_BUILDER {
            get {
                return ResourceManager.GetString("FILE_TOOLS_ARCHIVE_BUILDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customization.
        /// </summary>
        internal static string FILE_TOOLS_CUSTOMIZATION {
            get {
                return ResourceManager.GetString("FILE_TOOLS_CUSTOMIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourites Editor.
        /// </summary>
        internal static string FILE_TOOLS_FAVOURITES_EDITOR {
            get {
                return ResourceManager.GetString("FILE_TOOLS_FAVOURITES_EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Collection.
        /// </summary>
        internal static string FILE_TOOLS_OBJECT_COLLECTION {
            get {
                return ResourceManager.GetString("FILE_TOOLS_OBJECT_COLLECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Tool.
        /// </summary>
        internal static string FILE_TOOLS_TRACK_TOOL {
            get {
                return ResourceManager.GetString("FILE_TOOLS_TRACK_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string FOLDER_CONTEXTMENU_EXPORT {
            get {
                return ResourceManager.GetString("FOLDER_CONTEXTMENU_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string FORM_CLOSING_CHECK_TEXT {
            get {
                return ResourceManager.GetString("FORM_CLOSING_CHECK_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Fusion Explorer.
        /// </summary>
        internal static string FORM_CLOSING_CHECK_TITLE {
            get {
                return ResourceManager.GetString("FORM_CLOSING_CHECK_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes to .
        /// </summary>
        internal static string FORM_CLOSING_SAVE_TEXT {
            get {
                return ResourceManager.GetString("FORM_CLOSING_SAVE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fusion Explorer.
        /// </summary>
        internal static string FORM_CLOSING_SAVE_TITLE {
            get {
                return ResourceManager.GetString("FORM_CLOSING_SAVE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nPlease update the application config file with correct path.
        /// </summary>
        internal static string HXD_NOT_FOUND_TEXT {
            get {
                return ResourceManager.GetString("HXD_NOT_FOUND_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fusion Explorer.
        /// </summary>
        internal static string HXD_NOT_FOUND_TITLE {
            get {
                return ResourceManager.GetString("HXD_NOT_FOUND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string ITEM_CONTEXTMENU_EXPORT {
            get {
                return ResourceManager.GetString("ITEM_CONTEXTMENU_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with HxD.
        /// </summary>
        internal static string ITEM_CONTEXTMENU_HXD {
            get {
                return ResourceManager.GetString("ITEM_CONTEXTMENU_HXD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string ITEM_CONTEXTMENU_IMPORT {
            get {
                return ResourceManager.GetString("ITEM_CONTEXTMENU_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string ITEM_CONTEXTMENU_INFO {
            get {
                return ResourceManager.GetString("ITEM_CONTEXTMENU_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved .
        /// </summary>
        internal static string SAVED_CHANGES_LABEL_TEXT {
            get {
                return ResourceManager.GetString("SAVED_CHANGES_LABEL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string TEXTURE_CONTEXTMENU_EXPORT {
            get {
                return ResourceManager.GetString("TEXTURE_CONTEXTMENU_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export DDS.
        /// </summary>
        internal static string TEXTURE_CONTEXTMENU_EXPORT_DDS {
            get {
                return ResourceManager.GetString("TEXTURE_CONTEXTMENU_EXPORT_DDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with HxD.
        /// </summary>
        internal static string TEXTURE_CONTEXTMENU_HXD {
            get {
                return ResourceManager.GetString("TEXTURE_CONTEXTMENU_HXD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string TEXTURE_CONTEXTMENU_IMPORT {
            get {
                return ResourceManager.GetString("TEXTURE_CONTEXTMENU_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace DDS.
        /// </summary>
        internal static string TEXTURE_CONTEXTMENU_IMPORT_DDS {
            get {
                return ResourceManager.GetString("TEXTURE_CONTEXTMENU_IMPORT_DDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string TEXTURE_CONTEXTMENU_INFO {
            get {
                return ResourceManager.GetString("TEXTURE_CONTEXTMENU_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string TEXTURE_CONTEXTMENU_VIEW {
            get {
                return ResourceManager.GetString("TEXTURE_CONTEXTMENU_VIEW", resourceCulture);
            }
        }
    }
}
